#
# $Id$
#
# Defines stuff common to this entire code tree

# this tells the build system where to install shared libraries built from
# this code tree
LIBDIR = $(ROOT)/../lib/$(ARCH)

# where we put our zip and jar files
ZIPDIR = $(ROOT)/../lib

LOCAL_CLASSPATH += \
	$(shell ls $(ZIPDIR)/*.jar) \

#	$(shell ls $(ZIPDIR)/*.zip) \
